sequenceDiagram
  participant User
  participant PresentationLayer
  participant BusinessLogicLayer
  participant PersistenceLayer

  User->>PresentationLayer: Creates a new place with title, description, price, location, ownerId
  PresentationLayer->>BusinessLogicLayer: Validates data and creates place object

  alt Validation success

  
    BusinessLogicLayer->>PersistenceLayer: Saves place data to database
    BusinessLogicLayer->>AuditLogs: Log the new place creation          
        AuditLogs-->>PersistenceLayer:Returns success
  
    PersistenceLayer-->>BusinessLogicLayer: Returns success

    BusinessLogicLayer-->>PresentationLayer: Returns success message
    PresentationLayer-->>User: Returns success message


  else Validation failure
      AuditLogs-->>PersistenceLayer:Returns failed
          PersistenceLayer-->>BusinessLogicLayer: Returns failed
    BusinessLogicLayer-->>PresentationLayer: Returns validation error
    PresentationLayer-->>User: Returns error message
  end
